[2021-01-02 21:27:39,285][server.py:98][INFO]: server init
[2021-01-02 21:27:39,290][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-02 21:27:39,296][server.py:108][INFO]: server ready
[2021-01-02 21:27:49,406][_server.py:445][ERROR]: Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "C:\Users\86186\AppData\Local\Programs\Python\Python36\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "D:\demo\demo_python\opencv_python_code\grpc_opencv\server\proto\opencv_proto\opencv_pb2_grpc.py", line 31, in RunOpenCV
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
[2021-01-02 21:29:23,486][server.py:98][INFO]: server init
[2021-01-02 21:29:23,491][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-02 21:29:23,495][server.py:108][INFO]: server ready
[2021-01-02 21:29:27,372][log.py:15][ERROR]: trace_id: 89444b42-4cfe-11eb-836b-18cf5ea622c6, error_code: -10006, image_url:  opencv reg failed: Traceback (most recent call last):
  File "D:\demo\demo_python\opencv_python_code\grpc_opencv\server\opencv_rcg.py", line 69, in inference
    score = np.mean(image_buffer)
  File "C:\Users\86186\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\fromnumeric.py", line 3118, in mean
    out=out, **kwargs)
  File "C:\Users\86186\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\_methods.py", line 75, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: cannot perform reduce with flexible type

[2021-01-02 21:29:27,374][server.py:92][INFO]: request info: trace_id: 89444b42-4cfe-11eb-836b-18cf5ea622c6, client: 127.0.0.1:58228 error_code: -10006, cose: 0.02698493003845215, image_url: 
[2021-01-02 21:29:44,863][log.py:15][ERROR]: trace_id: 93b51ea4-4cfe-11eb-8cd9-18cf5ea622c6, error_code: -10006, image_url:  opencv reg failed: Traceback (most recent call last):
  File "D:\demo\demo_python\opencv_python_code\grpc_opencv\server\opencv_rcg.py", line 69, in inference
    score = np.mean(image_buffer)
  File "C:\Users\86186\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\fromnumeric.py", line 3118, in mean
    out=out, **kwargs)
  File "C:\Users\86186\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\_methods.py", line 75, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: cannot perform reduce with flexible type

[2021-01-02 21:29:44,863][server.py:92][INFO]: request info: trace_id: 93b51ea4-4cfe-11eb-8cd9-18cf5ea622c6, client: 127.0.0.1:58231 error_code: -10006, cose: 0.0009808540344238281, image_url: 
[2021-01-02 21:31:01,460][server.py:98][INFO]: server init
[2021-01-02 21:31:01,465][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-02 21:31:01,470][server.py:108][INFO]: server ready
[2021-01-02 21:31:05,073][log.py:15][ERROR]: trace_id: c383f2b0-4cfe-11eb-9aa0-18cf5ea622c6, error_code: -10006, image_url:  opencv reg failed: Traceback (most recent call last):
  File "D:\demo\demo_python\opencv_python_code\grpc_opencv\server\opencv_rcg.py", line 69, in inference
    score = np.mean(string_to_cvmat(image_buffer))
  File "D:\demo\demo_python\opencv_python_code\grpc_opencv\server\utils.py", line 23, in string_to_cvmat
    nparr = np.formstring(imagebuf, np.uint8)
AttributeError: module 'numpy' has no attribute 'formstring'

[2021-01-02 21:31:05,074][server.py:92][INFO]: request info: trace_id: c383f2b0-4cfe-11eb-9aa0-18cf5ea622c6, client: 127.0.0.1:58238 error_code: -10006, cose: 0.002017974853515625, image_url: 
[2021-01-02 21:31:53,098][server.py:98][INFO]: server init
[2021-01-02 21:31:53,103][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-02 21:31:53,107][server.py:108][INFO]: server ready
[2021-01-02 21:31:56,090][server.py:92][INFO]: request info: trace_id: e1e8f47e-4cfe-11eb-9274-18cf5ea622c6, client: 127.0.0.1:58241 error_code: 0, cose: 0.022985458374023438, image_url: 
[2021-01-02 21:32:11,347][server.py:92][INFO]: request info: trace_id: eb030df0-4cfe-11eb-b01f-18cf5ea622c6, client: 127.0.0.1:58244 error_code: 0, cose: 0.01501011848449707, image_url: 
[2021-01-03 09:32:20,909][server.py:98][INFO]: server init
[2021-01-03 09:32:20,914][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-03 09:32:20,917][server.py:108][INFO]: server ready
[2021-01-03 09:32:24,972][server.py:92][INFO]: request info: trace_id: 8856fe4a-4d63-11eb-8928-18cf5ea622c6, client: 127.0.0.1:49400 error_code: 0, cose: 0.013993024826049805, image_url: 
[2021-01-03 09:32:28,972][server.py:92][INFO]: request info: trace_id: 8ab93f46-4d63-11eb-8b1a-18cf5ea622c6, client: 127.0.0.1:49401 error_code: 0, cose: 0.014990806579589844, image_url: 
[2021-01-03 09:32:53,531][server.py:98][INFO]: server init
[2021-01-03 09:32:53,536][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-03 09:32:53,541][server.py:105][INFO]: server ready
[2021-01-03 09:32:59,653][server.py:92][INFO]: request info: trace_id: 9d01ddc2-4d63-11eb-9f09-18cf5ea622c6, client: 127.0.0.1:49403 error_code: 0, cose: 0.015990734100341797, image_url: 
[2021-01-03 09:33:23,352][server.py:97][INFO]: server init
[2021-01-03 09:33:23,358][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-03 09:33:23,364][server.py:104][INFO]: server ready
[2021-01-03 09:33:27,442][server.py:91][INFO]: request info: trace_id: ad926800-4d63-11eb-8924-18cf5ea622c6, client: 127.0.0.1:49405 error_code: 0, cose: 0.01598668098449707, image_url: 
[2021-01-03 09:33:44,069][server.py:96][INFO]: server init
[2021-01-03 09:33:44,074][server.py:46][INFO]: OpenCV Servicer init.
[2021-01-03 09:33:44,079][server.py:103][INFO]: server ready
[2021-01-03 09:33:46,880][server.py:90][INFO]: request info: trace_id: b928f43e-4d63-11eb-86be-18cf5ea622c6, client: 127.0.0.1:49408 error_code: 0, cose: 0.015007257461547852, image_url: 
